
platform :ios, ‘8.0’
use_frameworks!
workspace 'ReactiveCocoa3Demo'
inhibit_all_warnings!
target 'ReactiveCocoa3Demo' do
platform :ios, ‘8.0’
pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'
pod 'AFNetworking', '3.0.4'
pod 'YYWebImage', '~> 0.9.12'
end



